### ISSUE TITLE
A question about workflow

### ISSUE THREAD

**Issue by yuxuanz777** [16131zzzzzzzz/EveryoneNobel#1]
Hi I'm implementing the workflow (from Liblib) in ComfyUI, I use ComfyUI-Manager to install the missing custom nodes. But there are some import issue which I don't know how to solve.
![image](https://github.com/user-attachments/assets/46c5ba9c-3fc5-412b-a610-0e5414f13a2f)
Could you give me some suggestions on it? Thank you!

**Comment by 16131zzzzzzzz** [comment]
Every time I meet ComfyUI problems I just update my ComfyUI. If it still not works, we need your terminal screenshot.
