### ISSUE TITLE
Question on Model Training

### ISSUE THREAD

**Issue by JunZhan2000** [16131zzzzzzzz/EveryoneNobel#10]
Hello, very interesting work. 

I have a technical question. Previously, I also wanted to do style transfer for faces based on SD to create avatars, which is actually quite similar to what you are doing. However, the results I achieved from my training were quite poor. So I’m curious about how you trained your model. Do you need paired data for this? And how much data is required?

**Comment by bs001l** [comment]
During training, I only used a dataset of 24 images. The key, however, was likely in the detailed descriptions of the art style and specific details about the character used during annotation. When using the model, I include almost all the art style descriptions as trigger words. It’s not the smartest approach, but it’s relatively reliable.
