### ISSUE TITLE
Get Trouble in Workflow running 

### ISSUE THREAD

**Issue by niceTeen84** [16131zzzzzzzz/EveryoneNobel#12]
when i choose a image to run workflow get error info like this
![image](https://github.com/user-attachments/assets/368c4b5a-2fcf-46df-acf7-c9fb315b2155)
term output 
![image](https://github.com/user-attachments/assets/3716ba73-86c8-4379-82ba-cfbaea076ed9)

**Comment by Bonjir** [comment]
is that your photo? that's cool

**Comment by Bonjir** [comment]
i got the same problem with you, "prompt_outputs_failed_validation"

**Comment by 16131zzzzzzzz** [comment]
See #6

**Comment by niceTeen84** [comment]
> is that your photo? that's cool
照片上的人可能是我，不过照片上的人是我有点不太可能。🤣
Yes, But Impossile.
He is our chinese Arnold Schwarzenegger, we call him ChangShu Arnold.

**Comment by niceTeen84** [comment]
> See #6

Thank you!
