### ISSUE TITLE
Workflow Cannot open

### ISSUE THREAD

**Issue by Dramano** [16131zzzzzzzz/EveryoneNobel#2]
I tried to open workflow in `resources/workflow/nobel_workflow.json` with `ComfyUI`, but I just got the warnings for missing nodes, and the workflow wasn't loaded. In this case, I cannot install missing nodes with the `Manager`. I also tried other workflows, which can be loaded normally.
![image](https://github.com/user-attachments/assets/341b9cd1-16ab-4a6c-a22c-09666d22bb75)

**Comment by Torian2002** [comment]
I have the same problem. 🤨 Have you already solved it?

**Comment by Dramano** [comment]
> I have the same problem. 🤨 Have you already solved it?

not yet

**Comment by guozijing-zjk** [comment]
i also meet this problem........

**Comment by ssssssqy** [comment]
me too

**Comment by Torian2002** [comment]
想再提问一下，出问题的大家是macOS系统嘛～

**Comment by 16131zzzzzzzz** [comment]
Maybe it is because of the comfy version or because the json inside the repo is an api workflow. 
You can try to 
1) update the entire comfyui 
2) download the workflow in liblib and install the missing nodes
If these are not working, I need your terminal output.

**Comment by biigthinker** [comment]
Same problem with MacOS

**Comment by 16131zzzzzzzz** [comment]
We've add the nobel_workflow_for_install.json. Try to install missing nodes using this workflow.

**Comment by biigthinker** [comment]
<img width="1110" alt="iShot_2024-10-28_14 24 32" src="https://github.com/user-attachments/assets/39170b95-8617-433b-8b7b-185194cde566">
This issue is coming with the load of "nobel_workflow_for_install.json".
I am quite sure that I have downloaded and placed all the models according to your installation guide.

**Comment by biigthinker** [comment]
<img width="743" alt="image" src="https://github.com/user-attachments/assets/97d704c1-59dc-4c52-87f4-3c65f5c77666">
Here's a screenshot of my terminal

**Comment by 16131zzzzzzzz** [comment]
> <img alt="iShot_2024-10-28_14 24 32" width="1110" src="https://private-user-images.githubusercontent.com/98293213/380600669-39170b95-8617-433b-8b7b-185194cde566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjI2MzUsIm5iZiI6MTczMDIyMjMzNSwicGF0aCI6Ii85ODI5MzIxMy8zODA2MDA2NjktMzkxNzBiOTUtODYxNy00MzNiLThiN2ItMTg1MTk0Y2RlNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE3MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjQyMDRiMWM3NjM1NThlMjcyOWViZjlkNmQzZmI0MjI1MDJlZTA0YjgyMDJmMGQ3ZjRlNjg1ZjIyMmJhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GdAh_nLb3M5TLQaAesCH4E7CLNReRbyeK7SYuYQgQgU"> This issue is coming with the load of "nobel_workflow_for_install.json". I am quite sure that I have downloaded and placed all the models according to your installation guide.

I wonder if you still can not open the workflow `nobel_workflow_for_install.json` or just missing the nodes. If the workflow is loaded with missing nodes, you can use manager to install missing nodes. If the workflow can not be loaded into comfyui when there are missing nodes, it is a ComfyUI Error.

**Comment by LinkCut-World** [comment]
![image](https://github.com/user-attachments/assets/aa826160-1567-4022-b128-307ca8364d84)

I have the same problem. There is no 'Manager' in the side bar for me to install missing nodes.

**Comment by 16131zzzzzzzz** [comment]
https://github.com/ltdrdata/ComfyUI-Manager

**Comment by LinkCut-World** [comment]
Thank you. A big progress was made. But some error occurs when I run main.py:

```
D:\EveryoneNobel-main>python main_without_openai.py --name "somebody"  --subject "2024 nobel prize" --content "Do nothing" --image_path "resources/test/test.jpg" --comfy_server_address "127.0.0.1:6006"
{'name': 'somebody', 'content': '2024 nobel prize', 'image_path': 'resources/test/test.jpg', 'contribution': 'Do nothing', 'output_image_path': 'D:\\EveryoneNobel-main\\output\\somebody\\nobel_somebody_test.jpg'}
start comfy
Progess:  1 / 29  Tasks done
Progess:  2 / 29  Tasks done
Progess:  3 / 29  Tasks done
Progess:  4 / 29  Tasks done
Traceback (most recent call last):
  File "D:\EveryoneNobel-main\src\server.py", line 101, in generate_image_by_prompt_and_image
    save_image(images, output_path, save_previews)
  File "D:\EveryoneNobel-main\src\server.py", line 196, in save_image
    itm = images[-1]
          ~~~~~~^^^^
IndexError: list index out of range
```

**Comment by LinkCut-World** [comment]
Now I run again but it fails on task 3 instead of task 4.

More details for ComfyUI:

```
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3596.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
!!! Exception during processing !!! We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
```

It seems like internet connection error?

**Comment by 16131zzzzzzzz** [comment]
> Now I run again but it fails on task 3 instead of task 4.
> 
> More details for ComfyUI:
> 
> ```
> D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3596.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> final text_encoder_type: bert-base-uncased
> !!! Exception during processing !!! We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
> Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
> Traceback (most recent call last):
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
>     raise err
>   File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
>     sock.connect(sa)
> TimeoutError: timed out
> ```
> 
> It seems like internet connection error?

It seems to be a comfyui error which can caused by anything. According to your log, you are not able to connect huggingface. It can be solved with using mirror stations. But as it seems that you know little about python and comfyui, you'd better learn some basic concepts of comfyui through tutorials in bilibili and use the portable versions of others.

**Comment by LinkCut-World** [comment]
Thank you. I think I've solved the problem
