### ISSUE TITLE
start  main_without_openai.py with ModuleNotFoundError issues

### ISSUE THREAD

**Issue by MatinxHT** [16131zzzzzzzz/EveryoneNobel#3]
I was already clicked 'pip install -r requirements.txt' and everythings goes fine.

but cmd run this: 'python main_without_openai.py  --name "somebody"  --subject "2024 nobel prize"   --content "Do nothing" --image_path "resources/test/test.jpg"  --comfy_server_address "127.0.0.1:8188" ' will return :

**ModuleNotFoundError: No module named 'bs4'**

and i am sure beautifulsoup4 is installed and my python version is 3.11.

dont know what is going on

**Comment by 16131zzzzzzzz** [comment]
That is strange. Recommending to reinstall your bs4.

**Comment by MatinxHT** [comment]
> That is strange. Recommending to reinstall your bs4.

Tried and not help. (sad

**Comment by 16131zzzzzzzz** [comment]
Maybe you can use python3 main_without blablabla instead of python
